casbin/casbin-editor

netlify.toml
package.json

Fix: https://github.com/casbin/casbin-editor/issues/53
Explain why a new command `build-localhost` is added:
Homepage in package.json makes the deploy fails:
https://stackoverflow.com/questions/55418728/issue-in-deployment-of-react-app-in-netlify
Signed-off-by: ErikQQY <2283984853@qq.com>

feat: Add netlify PR preview

---

.github/workflows/gh-pages.yml

ci: use yarn instead of npm

---

.gitignore
app/components/editor/index.tsx
app/utils/getCasbinVersion.js
generateCasbinVersionPlugin.js
next.config.mjs

Fix: https://github.com/casbin/casbin-editor/issues/105

feat: show Node-Casbin version in top-right corner

---

.github/workflows/release.yml
package.json

Fix: https://github.com/casbin/casbin-editor/issues/112
Based on the submitted type and content, semantic-release determines the changes in version number and generates corresponding release notes.

feat: add semantic-release to CI

---

.github/workflows/release.yml
package.json

Fix: https://github.com/casbin/casbin-editor/issues/110
**Workflow Name**
Build and Release Electron App
**Trigger condition**
This workflow is triggered when a label conforming to the v*.*. Format is pushed. Specifically, when you push a tag that conforms to the vX.Y.Z format (e.g. v1.0.0, v2.1.3, etc.), this workflow is automatically executed.
```
git tag v1.0.0
git push origin v1.0.0
```
**Required GitHub Secrets**
GH_TOKEN: GitHub token, which requires sufficient permissions to clone repositories, install dependencies, publish releases, and upload artifacts.
1. Generate a GitHub Token
- Click on your profile picture, and then select Settings.
- On the left-hand menu, select Developer settings.
- Select Personal access tokens.
- Create a new Token
- Select the required permissions (all …

feat: publish Electron App in GitHub releases

---

app/components/editor/index.tsx
app/page.tsx

fix: https://github.com/casbin/casbin-editor/issues/118
- Make editor's black boxes adjust height dynamically to fit browser window.
- Ensure equal height for the four black boxes (two rows, two columns).
- Remove scrollbars by adjusting the height of the editor to fit the screen.
- Maintain visibility of syntax check buttons, GitHub stars, and copyright notice at the bottom.
- Improve user experience by eliminating the need for scrolling when switching models and running tasks.
https://github.com/casbin/casbin-editor/assets/92775570/95b6f594-f6e4-450a-962f-aa93b2a2a5ec

feat: adjust editor height dynamically to fit browser window

---

app/components/editor/hooks/useRunTest.tsx
app/components/editor/index.tsx

fix: https://github.com/casbin/casbin-editor/issues/120

feat: Adjust response formatting to conditionally display 'Reason' field when not empty

---

app/components/editor/ButtonPlugin.ts

fix: Fix the ButtonWidget image display issue in Electron build

---

app/components/ModelEditor.tsx
app/components/editor/index.tsx

Fix: https://github.com/casbin/casbin-editor/issues/157

feat: make the syntax error more obvious

---

app/components/editor/hooks/useIndex.tsx
app/components/editor/hooks/useRunTest.tsx
app/components/editor/hooks/useShareInfo.tsx
app/components/editor/index.tsx
app/utils/contentExtractor.ts
messages/ar.json
messages/de.json
messages/en.json
messages/es.json
messages/fr.json
messages/id.json
messages/it.json
messages/ja.json
messages/ko.json
messages/ms.json
messages/pt.json
messages/ru.json
messages/tr.json
messages/vi.json
messages/zh-Hant.json
messages/zh.json
package.json
yarn.lock

Fix: https://github.com/casbin/casbin-editor/issues/160
- Success message (green)
- Error Message (Red)
- Loading/In Progress Message (Orange)
- Add a protection mechanism against repeated clicks for the verification and run buttons (within 2 seconds).

feat: remove "syntax validate" button, add toast message to run button

---

app/components/editor/hooks/useIndex.tsx
app/components/editor/hooks/useShareInfo.tsx

Fix bug introduced by PR: https://github.com/casbin/casbin-editor/pull/169
When users modify content while using the `basic`(ACL) model and generate a share link, there is an issue where the content does not update when opening this link.
In the original code, `useEffect` only depends on `modelKind`. If the shared content uses the `basic` `modelKind`, it will not trigger an update of `useEffect`, resulting in the data for `enforceContext` being unable to be passed through the sharing link.
Add a `triggerUpdate` state counter and include it in the `useEffect` dependencies to force content updates.

fix: ensure that shared content loads correctly under the basic model, fix bug introduced by PR: #169

---

app/components/ModelEditor.tsx
app/components/SidePanelChat.tsx
app/components/editor/index.tsx
app/model-editor/page.tsx
app/utils/contentExtractor.ts

fix: https://github.com/casdoor/casdoor/issues/3426

feat: Improve the advanced editor on the Casdoor model editing page

---

app/components/editor/casbin-mode/example.ts

Fix: https://github.com/casbin/casbin-editor/issues/184
- `matchingForGFunction` and `matchingDomainForGFunction` can affect the logic of role matching and domain matching, potentially leading to results that do not align with expectations.
- Remove the default loaded `matchingForGFunction` and `matchingDomainForGFunction.`

feat: fix the bug that `matchingForGFunction` and `matchingDomainForGFunction` can affect the logic of role matching and domain matching

---

app/components/editor/casbin-mode/example.ts
package.json
yarn.lock

fix: https://github.com/casbin/casbin-editor/issues/193
- In the ABAC model, the reason in the return value of enforceEx may be undefined.
- Not handling this situation will lead to a type mismatch error.
- Return an empty array `[]` when reason is undefined.

feat: fix undefined reason in ABAC enforceEx result in Node.js engine

---

app/components/editor/casbin-mode/example.ts

fix: https://github.com/casbin/casbin-editor/issues/198

feat: add keymatch3, keymatch4, and keymatch5 to model list

---

app/components/editor/CasbinEngine.ts
app/components/editor/hooks/useEngineVersions.ts
app/components/editor/hooks/useRemoteEnforcer.ts
app/components/editor/index.tsx

fix: https://github.com/casbin/casbin-editor/issues/200

feat: show engine and CLI versions in engine dropdown widget

---

app/components/ModelEditor.tsx
app/components/editor/hooks/useRunTest.tsx
app/components/editor/index.tsx
app/utils/casbinLinter.ts
app/utils/errorHandler.ts
app/utils/errorManager.ts

Fix: https://github.com/casbin/casbin-editor/issues/174
- Introduced a classification system based on error types (MODEL/POLICY/REQUEST)  
- Added an error parser (parseError) to handle error messages  
- Implemented dedicated linters for different editors

feat: Enhance error handling with type-specific linters and error parsing

---

app/components/editor/CustomConfigPanel.tsx

The original layout utilized a fixed height of `height: 100vh` and `maxHeight: 50%`, which results in a less flexible layout on mobile devices.
Before:
After:

fix: improve custom function panel layout flexibility

---

app/components/editor/common/EndpointSelector.tsx
app/components/editor/common/EngineSelector.tsx
app/components/editor/common/FileUploadButton.tsx
app/components/editor/core/EngineSelector.tsx
app/components/editor/index.tsx
app/components/editor/panels/PolicyToolbar.tsx
app/components/hooks/useRemoteEnforcer.ts
app/components/ui/tooltip.tsx
app/globals.css
app/utils/lib/utils.ts
components.json
messages/ar.json
messages/de.json
messages/en.json
messages/es.json
messages/fr.json
messages/id.json
messages/it.json
messages/ja.json
messages/ko.json
messages/ms.json
messages/pt.json
messages/ru.json
messages/tr.json
messages/vi.json
messages/zh-Hant.json
messages/zh.json
package.json
tailwind.config.ts
yarn.lock

Fix: https://github.com/casbin/casbin-editor/issues/218

feat: support selecting different Casbin engine endpoints and use icons to enhance UI

---

app/components/hooks/useRemoteEnforcer.ts

fix: https://github.com/casdoor/casdoor/issues/3534
- Keep full ISO timestamp format to match RFC3339
- Remove URL encoding to match backend string handling

fix: align identifier generation with backend implementation

---

app/components/editor/common/EngineSelector.tsx
app/components/editor/core/CasbinEngine.ts
app/components/editor/index.tsx
app/components/editor/panels/PolicyToolbar.tsx
app/components/hooks/useEngineVersions.ts
app/components/hooks/useIndex.tsx
app/components/hooks/useRemoteEnforcer.ts
app/components/hooks/useRunTest.tsx
app/config/engineConfig.ts
app/utils/resultFormatter.ts
test/casbinEngine.test.ts

fix: https://github.com/casbin/casbin-editor/issues/225
- Created centralized engine configuration in `app/config/engineConfig.ts`

refactor: centralize engine configuration and type definitions

---

app/components/editor/index.tsx
app/components/hooks/useEnforceCall.ts
app/components/hooks/useEngineVersions.ts

The previous version acquisition depends on the `isLoading` state, and each `enforce` operation will trigger version re-acquisition, consuming api requests
Decouple version fetching from the `loading` state of the `enforce` operation.

fix: resolve duplicate request issue
