- .github/workflows/gh-pages.yml
> Add gh-pages workflow

- package.json
- src/editor/run-test.tsx
Fix: https://github.com/casbin/casbin-website/issues/78#issuecomment-639937432
> bump casbin to 5.0.3

- src/editor/run-test.tsx
relate: https://github.com/casbin/casbin-website/issues/78#issuecomment-640045516
close #10
> fix: invalid policy in abac model

- src/editor/index.tsx
> fix: repeatedly hide the custom configuration container

- src/editor/persist.ts
> Fix reset button

- src/editor/index.tsx
> fix: improve visibility of CustomConfig

- src/editor/casbin-mode/example.ts
> fix: format example

- src/editor/casbin-mode/example.ts
- src/editor/editor.tsx
- src/editor/index.tsx
- src/editor/run-test.tsx
- src/editor/settings.tsx
- src/editor/use-local-storage.tsx
Fix: https://github.com/casbin/casbin-editor/issues/31
> fix: add settings

- package.json
- yarn.lock
Fix: https://github.com/casbin/node-casbin/issues/269, https://github.com/casbin/casbin-editor/issues/34
> fix: update casbin

- src/editor/casbin-mode/example.ts
- src/editor/editor.tsx
- src/editor/persist.ts
- src/editor/settings.tsx
Fix: https://github.com/casbin/casbin-editor/issues/42
@hsluoyz @nodece plz review
> fix: resolve config refresh

- src/editor/run-test.tsx
Fix: https://github.com/casbin/casbin-editor/issues/45
Fix: https://github.com/php-casbin/php-casbin/issues/90
@techoner @nodece @hsluoyz plz review
> fix: resolve unexpected parse

- package.json
- src/editor/run-test.tsx
- yarn.lock
resolve: #47 
@hsluoyz @nodece plz review
> feat: add keyGet and keyGet2

- src/editor/run-test.tsx
- yarn.lock
With the patch, parser will handle space correctly even when it works
with object.
@hsluoyz @nodece plz review
> perf: enhance parser and regenerate yarn.lock

- src/editor/copy.tsx
- src/editor/editor.tsx
- src/editor/index.tsx
- src/editor/settings.tsx
- src/editor/share.tsx
- src/editor/use-local-storage.tsx
- yarn.lock
resolve: #44 
@hsluoyz @nodece plz review
> feat: add support for share content

- src/editor/run-test.tsx
about: #57 
@nodece @hsluoyz plz review
> fix: fix unexpect parse

- package.json
- yarn.lock
Closes https://github.com/casbin/casbin-editor/issues/57
> build: update version of casbin

- package.json
- yarn.lock
resolve: #60 
@nodece plz review
> build: update casbin

- package.json
- src/editor/run-test.tsx
- src/editor/syntax.tsx
- yarn.lock
> fix: use casbin.js@next instead of casbin

- package.json
- src/editor/run-test.tsx
- src/editor/syntax.tsx
- yarn.lock
> build: upgrade casbin

- package.json
fix: https://github.com/casbin/casbin-editor/issues/78
> fix: fix the deployment directory

- craco.config.js
- package.json
- src/editor/run-test.tsx
- yarn.lock
Fix: https://github.com/casbin/casbin-editor/issues/86
Upgrade casbin to latest version.
> feat: upgrade casbin to latest v5.26.1

- src/editor/casbin-mode/example.ts
- src/editor/index.tsx
- src/editor/persist.ts
- src/editor/run-test.tsx
- src/editor/setup-enforce-context.tsx
- src/editor/share.tsx
> feat: add enforce context

- next.config.mjs
> fix: nextjs basePath config

- README.md
- package.json
fix: update README.md to fit nextjs dev and production
> fix: update README.md to fit nextjs dev and production

- app/components/editor/index.tsx
Fix: https://github.com/casbin/casbin-editor/issues/101
> fix: update the result directly when switching options

- package.json
- yarn.lock
After the upgrade package testing, everything is functioning properly.
> feat: update casbin to version 5.30.0

- README.md
Fix: https://github.com/casbin/casbin-editor/issues/114
> feat: Update badges

- main.js
Remove unnecessary code.
Remove it and it will show up fine on Win
> fix: windows - Fixed issue with electron Windows program opening blank

- app/components/editor/hooks/useIndex.tsx
- app/components/editor/hooks/useShareInfo.tsx
- app/components/editor/index.tsx
- next.config.mjs
fix: https://github.com/casbin/casbin-editor/issues/131
> feat: fix bug that unable to find matchers in model

- app/components/LanguageMenu.tsx
- app/components/editor/index.tsx
- app/context/LangContext.tsx
Fix: https://github.com/casbin/casbin-editor/issues/137
> feat: Support dark mode better

- app/components/editor/index.tsx
- app/layout.tsx
- app/page.tsx
Fix: https://github.com/casbin/casbin-editor/issues/143
Mobile:
> feat: Support mobile view better

- app/context/LangContext.tsx
Fix: https://github.com/casbin/casbin-editor/issues/145
> feat: the editor language doesn't follow the casbin-website language

- app/components/SidePanelChat.tsx
fix: https://github.com/casbin/casbin-editor/issues/147
> feat: The "Ask AI" pop-up doesn't look well in mobile view

- app/components/editor/hooks/useRunTest.tsx
- app/components/editor/index.tsx
- app/utils/casbinLinter.ts
- app/utils/errorManager.ts
- package.json
- yarn.lock
Fix: https://github.com/casbin/casbin-editor/issues/149
> feat: show the error in the right box

- app/components/editor/casbin-mode/casbin-conf.ts
fix:https://github.com/casbin/casbin-editor/issues/155
> feat: the model matcher highlight bug

- package.json
- yarn.lock
Fix: https://github.com/casbin/casbin-editor/issues/159
> feat: update casbin dependency to version 5.31.0

- package.json
- yarn.lock
Fix: https://github.com/casbin/casbin-editor/issues/164
Integate with PR: https://github.com/casbin/node-casbin/pull/494
> feat: update casbin dependency to v5.36.0 to fix CSV parser issue

- app/components/ModelEditor.tsx
Part of: https://github.com/casdoor/casdoor/issues/3429
This PR adds language synchronization support for the iframe editor component, allowing it to receive and handle language changes from the parent window.
> feat: support language sync in iframe editor

- app/components/ModelEditor.tsx
Improve the reset function in the model editor.
> feat: improve model editor reset functionality

- app/components/editor/hooks/useRemoteEnforcer.ts
- app/components/editor/hooks/useRunTest.tsx
- app/components/editor/index.tsx
Part of: https://github.com/casbin/casbin-editor/issues/129
> feat: support jCasbin backend

- app/components/ModelEditor.tsx
- app/components/editor/CasbinEngine.ts
- app/components/editor/casbin-mode/example.ts
- app/components/editor/hooks/useIndex.tsx
- app/components/editor/hooks/useRemoteEnforcer.ts
- app/components/editor/hooks/useRunTest.tsx
- app/components/editor/index.tsx
- app/utils/casbinEnforcer.ts
- app/utils/casbinRequestParser.ts
fix: https://github.com/casbin/casbin-editor/issues/179
A unified Casbin engine interface (ICasbinEngine) has been implemented to abstract the common behaviors of different Casbin implementations (Node.js, Java, Go). Additionally, the related code has been refactored to improve maintainability.
1. Create CasbinEngine.ts
- Define the ICasbinEngine interface.
- Implement NodeCasbinEngine for browser-side execution.
- Implement RemoteCasbinEngine for remote calls to Java/Go versions.
- Provide the createCasbinEngine factory function.
2. Refactor useRunTest.tsx
- Remove duplicate execution logic.
- Use the CasbinEngine interface to handle requests uniformly.
- Improve error handling and performance measurement.
3. Optimize useRemoteEnforcer.ts
- Improve response format handling.
- Standardize …
> feat: Implement a unified Casbin engine interface and refactor the execution logic.

- app/components/editor/LoadingOverlayExtension.ts
- app/components/editor/index.tsx
fix: https://github.com/casbin/casbin-editor/issues/190
> feat: add response window's loading UI for engine selection

- app/components/editor/MessageWithTooltip.tsx
- app/components/editor/index.tsx
fix: https://github.com/casbin/casbin-editor/issues/206
> feat: fix too long error breaking UI

- app/components/editor/casbin-mode/example.ts
- test/casbinEngine.test.ts
fix: https://github.com/casbin/casbin-editor/issues/205
> fix: handle JSON parsing in request parameters

- app/components/editor/casbin-mode/example.ts
fix: https://github.com/casbin/casbin-editor/issues/209
> feat: add new RBAC examples with domains, time constraints, tags, resource filters, multiple roles, and deny rules

- app/components/hooks/useRemoteEnforcer.ts
Part of: https://github.com/casdoor/casdoor/issues/3534
> feat: use identifier query param

- app/components/editor/common/EngineSelector.tsx
- app/components/editor/core/CasbinEngine.ts
- app/components/editor/index.tsx
- app/components/editor/panels/PolicyToolbar.tsx
- app/components/hooks/useEngineVersions.ts
- app/components/hooks/useRemoteEnforcer.ts
- app/utils/resultFormatter.ts
- test/casbinEngine.test.ts
fix: https://github.com/casbin/casbin-editor/issues/219
> feat: support casbin-rust-cli engine

- test/casbinEngine.test.ts
Fix: https://github.com/casbin/casbin-editor/actions/runs/13216433975
> test: increase timeout for casbin engine tests

- app/components/editor/index.tsx
- app/components/editor/panels/FooterToolbar.tsx
- app/components/editor/panels/ModelToolbar.tsx
- app/components/editor/panels/PolicyToolbar.tsx
- app/components/editor/panels/RequestToolbar.tsx
- app/components/editor/panels/SidePanelChat.tsx
fix: https://github.com/casbin/casbin-editor/issues/233
> feat: when the sidebar is open, the editor is fully displayed.

- app/components/editor/casbin-mode/example.ts
Fix: https://github.com/casbin/casbin/issues/1500
> feat: add ReBAC example

- app/config/engineConfig.ts
- test/casbinEngine.test.ts
Fix: https://github.com/casbin/casbin-editor/issues/238
> feat: add PyCasbin (Python) engine to editor

- app/config/engineConfig.ts
Fix: https://github.com/casbin/casbin-editor/issues/246
> feat: add Casbin.NET (C#) engine to editor
